"""add locking and announcements

Revision ID: 173c138858a7
Revises: 8efabcb2601c
Create Date: 2026-04-04 00:19:01.316273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '173c138858a7'
down_revision: Union[str, Sequence[str], None] = '8efabcb2601c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('recipient_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('scholar_id', sa.UUID(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pending_changes', sa.Column('claimed_by', sa.UUID(), nullable=True))
    op.add_column('pending_changes', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.add_column('pending_changes', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'pending_changes', 'users', ['claimed_by'], ['id'])
    op.create_foreign_key(None, 'pending_changes', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_changes', type_='foreignkey')
    op.drop_constraint(None, 'pending_changes', type_='foreignkey')
    op.drop_column('pending_changes', 'assigned_to')
    op.drop_column('pending_changes', 'claimed_at')
    op.drop_column('pending_changes', 'claimed_by')
    op.drop_table('announcement_receipts')
    op.drop_table('announcements')
    # ### end Alembic commands ###
