"""phase 2 schema

Revision ID: 8efabcb2601c
Revises: 060a7711aa84
Create Date: 2026-04-03 23:38:53.783483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8efabcb2601c'
down_revision: Union[str, Sequence[str], None] = '060a7711aa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scholar_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('school_year', sa.String(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('student_type', sa.String(), nullable=True),
    sa.Column('remarks_status', sa.String(), nullable=True),
    sa.Column('unposted_count', sa.String(), nullable=True),
    sa.Column('inc_count', sa.String(), nullable=True),
    sa.Column('failed_count', sa.String(), nullable=True),
    sa.Column('submission_status', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scholar_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('evaluator_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholars.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scholar_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('year_level', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scholar_id', sa.UUID(), nullable=False),
    sa.Column('academic_record_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['academic_record_id'], ['academic_records.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospectus_grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('academic_record_id', sa.UUID(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('units', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['academic_record_id'], ['academic_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scholars', sa.Column('student_type', sa.String(), nullable=True))
    op.add_column('scholars', sa.Column('date_enrolled', sa.Date(), nullable=True))
    op.add_column('scholars', sa.Column('place_of_birth', sa.String(), nullable=True))
    op.add_column('scholars', sa.Column('sex', sa.String(), nullable=True))
    op.add_column('scholars', sa.Column('civil_status', sa.String(), nullable=True))
    op.add_column('scholars', sa.Column('religion', sa.String(), nullable=True))
    op.add_column('scholars', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('scholars', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholars', 'updated_at')
    op.drop_column('scholars', 'created_at')
    op.drop_column('scholars', 'religion')
    op.drop_column('scholars', 'civil_status')
    op.drop_column('scholars', 'sex')
    op.drop_column('scholars', 'place_of_birth')
    op.drop_column('scholars', 'date_enrolled')
    op.drop_column('scholars', 'student_type')
    op.drop_table('prospectus_grades')
    op.drop_table('documents')
    op.drop_table('program_history')
    op.drop_table('pending_changes')
    op.drop_table('academic_records')
    # ### end Alembic commands ###
